apiVersion: v1
kind: Service
metadata:
  name: {{ include "warden.fullname" . }}
  labels: {{- include "warden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "warden.selector" . | nindent 4 }}
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
